=== brian-m-rapp/akm2/data/games.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Version 0.2
	This DTD is the specification for the games.xml file, which contains non-OS
	specific information about each game.
 -->
<!ELEMENT games			(game+)>
<!ATTLIST games			version CDATA #REQUIRED>
<!ELEMENT game			(gamename,gameicon,servertype,defaultport,attribute*,cheatprotection?,mod*,ignoreothers?,ignore*)>
<!ATTLIST game			id ID #REQUIRED>
<!ELEMENT gamename		(#PCDATA)>
<!ELEMENT gameicon		(#PCDATA)>
<!ELEMENT servertype	(#PCDATA)>		<!-- q3s = q3 server with getstatus query, q3i = q3 server with getinfo query -->
<!ATTLIST servertype	authenticate CDATA #IMPLIED>
<!ELEMENT defaultport	(#PCDATA)>

<!-- Attributes are used to specify cvars that differ from the base game type standard.
	Server Attribute vars can have the following values:
		
	engineversion	(var for the game engine version)
	gametype		(var for game type - e.g.: ffa, ctf, tdm)
	gamename		(var for game mod)
	gameversion		(var for version of a mod engine as with Q3 OSP)
	modversion		(var for version of a mod for games like RA3, which use it as the discriminator)
	protocol		(var for network protocol ID)
	mapname			(var for the current map name)
	cheatprotection	(var for status of the cheat protection software such as punkbuster)
	needpassword	(var for whether or not a password is required to connect)
	servername		(var for the server name)
	timelimit		(var for the game time limit)
	maxclients		(var for the maximum number of clients allowed on the server

	Any values not specified will use the default cvar for the game.  
	(e.g. - for a quake3 derivative, sv_hostname will be used for the server name unless it is overridden  with a
	"servername" attribute).  The configuration for Nexuiz has some actual examples.

 -->
<!ELEMENT attribute		(#PCDATA)>
<!ATTLIST attribute		var CDATA #REQUIRED>
<!ELEMENT cheatprotection (#PCDATA)>

<!ELEMENT mod			(modname,modicon?,moddiscrim?,team1name?,team2name?,customnames?,gametype*)>
<!ATTLIST mod			id CDATA #REQUIRED>
<!ELEMENT ignoreothers	EMPTY>
<!ELEMENT ignore		(#PCDATA)>		<!-- uses the game discriminator to determine which mods/engines/etc to ignore -->
<!ATTLIST ignore		attrib	(mod|engine) "mod">

<!ELEMENT modname		(#PCDATA)>
<!ELEMENT modicon		(#PCDATA)>		<!-- if not specified, the game icon will be used -->
<!ELEMENT moddiscrim	(#PCDATA)>		<!-- gametype normally, or gameversion for ra3 -->
<!ELEMENT team1name		(#PCDATA)>
<!ELEMENT team2name		(#PCDATA)>
<!ELEMENT customnames	(#PCDATA)>		<!-- true or false -->
<!ELEMENT gametype		(#PCDATA)>
<!ATTLIST gametype		id CDATA #REQUIRED>

=== brian-m-rapp/akm2/data/games.linux.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE games SYSTEM "games.dtd" >

<games version="0.2">
	<game id="q3a">
		<gamename>Quake III Arena</gamename>
		<gameicon>quake3</gameicon>			<!--  For Linux/OSX, this will be a PNG file; for Windows, it will be a gif -->
		<servertype>q3s</servertype>
		<cheatprotection>punkbuster</cheatprotection>
		<mod id="baseq3">
			<modname>BaseQ3</modname>
			<moddiscrim>gametype</moddiscrim>
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
		</mod>
		<mod id="osp">
			<modname>OSP</modname>
			<modicon>osp</modicon>
			<moddiscrim>gametype</moddiscrim> 
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
			<gametype id="5">Clan Arena</gametype>
			<gametype id="6">Freeze Tag</gametype>
		</mod>
		<mod id="cpma">
			<modname>CPMA</modname>
			<modicon>cpma</modicon>
			<moddiscrim>gametype</moddiscrim> 
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
			<gametype id="5">Clan Arena</gametype>
			<gametype id="6">Freeze Tag</gametype>
			<gametype id="7">Capture Strike</gametype>
		</mod>
		<mod id="arena">
			<modname>Rocket Arena</modname>
			<modicon>ra3</modicon>
			<moddiscrim>gameversion</moddiscrim>
			<customnames>false</customnames>
			<gametype id="1.8b">1.8b</gametype>
			<gametype id="1.76a">1.76a</gametype>
			<gametype id="1.76">1.76</gametype>
		</mod>
		<mod id="threewave">
			<modname>Threewave</modname>
			<modicon>threewave</modicon>
			<moddiscrim>gametype</moddiscrim>
			<customnames>false</customnames>
			<gametype id="0">Threewave CTF</gametype>
			<gametype id="1">Classic CTF</gametype>
			<gametype id="2">Capture Strike</gametype>
			<gametype id="3">Threewave FFA</gametype>
			<gametype id="4">Threewave TDM</gametype>
		</mod>
		<mod id="beryllium">
			<modname>Beryllium</modname>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Blue</team1name>
			<team2name>Red</team2name>
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
		</mod>
		<mod id="defrag">
			<modname>DeFrag</modname>
			<moddiscrim>gametype</moddiscrim>
			<customnames>false</customnames>
			<gametype id="0">Auto Config</gametype>
			<gametype id="1">Single Player DeFrag</gametype>
			<gametype id="2">Single Player Tricks</gametype>
			<gametype id="3">Single Player Fastcaps</gametype>
			<gametype id="4">Multiplayer Defrag</gametype>
			<gametype id="5">Multiplayer Tricks</gametype>
			<gametype id="6">Multiplayer Fastcaps</gametype>
		</mod>
		<mod id="epic">
			<modname>Epic</modname>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Blue</team1name>
			<team2name>Red</team2name>
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
		</mod>
		<mod id="excessive">
			<modname>Excessive Plus</modname>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Blue</team1name>
			<team2name>Red</team2name>
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
		</mod>
		<mod id="freeze">
			<modname>Freeze Tag</modname>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Blue</team1name>
			<team2name>Red</team2name>
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
		</mod>
		<mod id="instaunlagged">
			<modname>Insta-Unlagged</modname>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Blue</team1name>
			<team2name>Red</team2name>
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
		</mod>
		<mod id="unlagged">
			<modname>Unlagged</modname>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Blue</team1name>
			<team2name>Red</team2name>
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
		</mod>
		<mod id="pkarena">
			<modname>Pain Keep Arena</modname>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Blue</team1name>
			<team2name>Red</team2name>
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
		</mod>
		<mod id="excessiveplus">
			<modname>Excessive Plus</modname>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Blue</team1name>
			<team2name>Red</team2name>
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
		</mod>
		<mod id="q3f2">
			<modname>Fortress 2</modname>
			<modicon>q3f</modicon>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Blue</team1name>
			<team2name>Red</team2name>
			<customnames>false</customnames>
			<gametype id="1">Tournament</gametype>
			<gametype id="2">FFA</gametype>
			<gametype id="3">TDN</gametype>
			<gametype id="4">CTF</gametype>
			<gametype id="5">Fortress</gametype>
		</mod>
		<mod id="ufreeze">
			<modname>Ultra Freeze Tag</modname>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Blue</team1name>
			<team2name>Red</team2name>
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
		</mod>
		<mod id="westernq3">
			<modname>Western Quake</modname>
			<modicon>wq3</modicon>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Blue</team1name>
			<team2name>Red</team2name>
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
		</mod>
		<mod id="battle">
			<modname>X-Battle</modname>
			<modicon>battle</modicon>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Blue</team1name>
			<team2name>Red</team2name>
			<customnames>false</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="1">Duel</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">CTF</gametype>
		</mod>
		<ignore attrib="mod">q3ut2</ignore>
		<ignore attrib="mod">q3ut3</ignore>
		<ignore attrib="mod">q3ut4</ignore>
		<ignore attrib="mod">q3ut42</ignore>
	</game>
	<game id="urt">
		<gamename>Urban Terror</gamename>
		<gameicon>q3ut</gameicon>
		<servertype>q3s</servertype>
		<mod id="q3ut2">
			<modname>Urban Terror 2</modname>
			<modicon>q3ut</modicon>
			<moddiscrim>gametype</moddiscrim>
			<customnames>true</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">TS</gametype>
			<gametype id="5">FTL</gametype>
			<gametype id="6">CAH</gametype>
			<gametype id="7">CTF</gametype>
			<gametype id="8">Bomb</gametype>
		</mod>
		<mod id="q3ut3">
			<modname>Urban Terror 3</modname>
			<modicon>q3ut</modicon>
			<moddiscrim>gametype</moddiscrim>
			<customnames>true</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">TS</gametype>
			<gametype id="5">FTL</gametype>
			<gametype id="6">CAH</gametype>
			<gametype id="7">CTF</gametype>
			<gametype id="8">Bomb</gametype>
		</mod>
		<mod id="q3ut4">
			<modname>Urban Terror 4</modname>
			<modicon>q3ut</modicon>
			<moddiscrim>gametype</moddiscrim>
			<customnames>true</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">TS</gametype>
			<gametype id="5">FTL</gametype>
			<gametype id="6">CAH</gametype>
			<gametype id="7">CTF</gametype>
			<gametype id="8">Bomb</gametype>
		</mod>
		<mod id="q3ut42">
			<modname>Urban Terror 4.2</modname>
			<modicon>q3ut</modicon>
			<moddiscrim>gametype</moddiscrim>
			<customnames>true</customnames>
			<gametype id="0">FFA</gametype>
			<gametype id="3">TDM</gametype>
			<gametype id="4">TS</gametype>
			<gametype id="5">FTL</gametype>
			<gametype id="6">CAH</gametype>
			<gametype id="7">CTF</gametype>
			<gametype id="8">Bomb</gametype>
		</mod>
		<ignoreothers />
	</game>
	<game id="wsw">
		<gamename>Warsow</gamename>
		<gameicon>warsow</gameicon>
		<servertype>q3i</servertype>
		<mod id="warsow">
			<modname>Warsow</modname>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Blue</team1name>
			<team2name>Red</team2name>
			<customnames>false</customnames>
			<gametype id="dm">FFA</gametype>
			<gametype id="duel">Duel</gametype>
			<gametype id="tdm">TDM</gametype>
			<gametype id="ctf">CTF</gametype>
			<gametype id="race">Race</gametype>
			<gametype id="insta">Instagib</gametype>
			<gametype id="ca">Clan Arena</gametype>
			<gametype id="da">Duel &amp; Quad</gametype>
		</mod>
	</game>
	<game id="rtcw">
		<gamename>Return to Castle Wolfenstein</gamename>
		<gameicon>rtcw</gameicon>
		<servertype>q3s</servertype>
		<cheatprotection>punkbuster</cheatprotection>
		<mod id="main">
			<modname>RTCW</modname>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Allies</team1name>
			<team2name>Axis</team2name>
			<customnames>false</customnames>
			<gametype id="5">Multi-Player</gametype>
			<gametype id="6">Stop Watch</gametype>
			<gametype id="7">Check Point</gametype>
		</mod>
		<mod id="s4ndmod">
			<modname>S4NDMod</modname>
			<moddiscrim>gametype</moddiscrim>
			<team1name>Allies</team1name>
